// Generated by CodiumAI

import { polygonPerimeter } from "../polygonPerimeter";
import { Vec2 } from "../Vec2";

describe("polygonPerimeter", () => {

    it("should calculate the perimeter of an open polygon", () => {
        // Arrange
        const polygon = [
            new Vec2(0, 0),
            new Vec2(0, 1),
            new Vec2(1, 1),
            new Vec2(1, 0)
        ];

        // Act
        const result = polygonPerimeter(polygon);

        // Assert
        expect(result).toBe(3);
    });

    it("should calculate the perimeter of a force-closed polygon", () => {
        // Arrange
        const polygon = [
            new Vec2(0, 0),
            new Vec2(0, 1),
            new Vec2(1, 1),
            new Vec2(1, 0)
        ];

        // Act
        const result = polygonPerimeter(polygon, true);

        // Assert
        expect(result).toBe(4);
    });

    it("should calculate the perimeter of a closed polygon", () => {
        // Arrange
        const polygon = [
            new Vec2(0, 0),
            new Vec2(0, 1),
            new Vec2(1, 1),
            new Vec2(1, 0),
            new Vec2(0, 0)
        ];

        // Act
        const result = polygonPerimeter(polygon, true);

        // Assert
        expect(result).toBe(4);
    });

});
